Project aims to create and publish Maven artifacts for sound processing libraries that are not deployed to Maven Central Repository by their original authors.
Since these projects are stable for several years (let's not call them dead, shall we?), it is unlikely that they switch to Maven anytime soon.

Following artifacts are released including source and javadoc artifacts:

  * http://tritonus.org[Tritonus share] - utility classes for sound processing
  * http://www.javazoom.net/javalayer/javalayer.html[JLayer] - MP3 decoder and  encoder 
  * http://www.javazoom.net/mp3spi/mp3spi.html[MP3SPI] - javax.sound provider for MP3 decoding and encoding based on JLayer
  * http://www.jcraft.com/jorbis/[JOrbis] - OGG Vorbis decoder and encoder
  * http://www.javazoom.net/vorbisspi/vorbisspi.html[VorbisSPI] - Service provider for decoding OGG Vorbis
  * http://www.javazoom.net/jlgui/api.html[BasicPlayer] - BasicPlayer layer is the simple player API of jlGui. These classes are designed to be used in any application that needs simple features (play, stop, pause, resume, seek) to play audio file or stream. It's a high-level API over JavaSound API.

== How to use

Add any of these dependencies to your project:

[code,xml]
----
<dependency>
  <groupId>com.googlecode.soundlibs</groupId>
  <artifactId>tritonus-share</artifactId>
  <version>0.3.7.4</version>
</dependency>

<dependency>
  <groupId>com.googlecode.soundlibs</groupId>
  <artifactId>tritonus-all</artifactId>
  <version>0.3.7.2</version>
</dependency>

<dependency>
  <groupId>com.googlecode.soundlibs</groupId>
  <artifactId>jlayer</artifactId>
  <version>1.0.1.4</version>
</dependency>

<dependency>
  <groupId>com.googlecode.soundlibs</groupId>
  <artifactId>mp3spi</artifactId>
  <version>1.9.5.3</version>
</dependency>

<dependency>
  <groupId>com.googlecode.soundlibs</groupId>
  <artifactId>jorbis</artifactId>
  <version>0.0.17.4</version>
</dependency>

<dependency>
  <groupId>com.googlecode.soundlibs</groupId>
  <artifactId>vorbisspi</artifactId>
  <version>1.0.3.3</version>
</dependency>

<dependency>
  <groupId>com.googlecode.soundlibs</groupId>
  <artifactId>basicplayer</artifactId>
  <version>3.0.0.0</version>
</dependency>
----

== Changes

=== soundlibs 1.4

* Released with https://github.com/danielflower/multi-module-maven-release-plugin[multimodule-release-plugin]
* Added BasicPlayer module
* mp3spi exports javazoom.spi package

Due to new release process all modules have are re-released with new version number. Packaging versions are no longer
separated with a dash, rather with a dot.

=== soundlibs 1.3

* Added OSGi support
* Added tritonus-all with all non-native code of tritonus
* Support input configuration in javazoom player